workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      android_signing:
        - com.esparkbiz.deploy_test
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.esparkbiz.deploy_test"
        GOOGLE_PLAY_TRACK: alpha
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Build AAB with Flutter
        script: |
          BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))      
          flutter build apk --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - prathvik.sankaliya.2024@gmail.com
          - prathviksankaliya@gmail.com
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true

  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    integrations:
      app_store_connect: eSparkBiz Technologies Private Limited
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.cicdmegic.app
      vars:
        APP_STORE_APPLE_ID: 6692628444
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.cicdmegic.app"
        xcode: 15.2
        cocoapods: default
      flutter: stable

    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Increment build number
        script: |
          # Navigate to the iOS directory where the Xcode project is located
          cd ios

          # Fetch the latest build number from App Store Connect (only the build number, not the version)
          latest_build_number=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID" | tr -d '[:space:]' || echo "0")

          # If the latest_build_number is empty or not a number, set it to 0
          if ! [[ "$latest_build_number" =~ ^[0-9]+$ ]]; then
            echo "Failed to fetch the latest build number, setting it to 0."
            latest_build_number=0
          fi

          # Increment the build number by 1
          new_build_number=$((latest_build_number + 1))
          echo "Setting new build number: $new_build_number"

          # Update the build number using agvtool
          agvtool new-version -all "$new_build_number"

          # Go back to the root directory for the next steps
          cd -
      - name: Clean build folder
        script: |
          # Ensure we are in the root of the Flutter project
          echo "Current directory: $(pwd)"
          echo "Listing root directory contents:"
          ls -la

          # Navigate to the iOS directory
          cd ios

          # Print current directory and list files to ensure correct navigation
          echo "Current directory after navigating to ios/: $(pwd)"
          echo "Listing ios/ directory contents:"
          ls -la

          # Clean previous build artifacts
          flutter clean

          # Reinstall Flutter dependencies and iOS pods
          flutter pub get
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number="$new_build_number" \
            --export-options-plist=/Users/builder/export_options.plist



    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - prathvik.sankaliya.2024@gmail.com
          - prathviksankaliya@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration

        # Configuration related to TestFlight (optional)
        # Note: This action is performed during post-processing.
        submit_to_testflight: true
        beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
          - group name 1
          - group name 2

        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
        submit_to_app_store: false